apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: josephsabanaacr.azurecr.io/product_service:main
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: azure-storage-secret
      imagePullSecrets:
      - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
