name: CI (testing) — Test, Build & Push

on:
  push:
    branches: [ testing ]

jobs:
  test_build_push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}
      IMAGE: ${{ secrets.IMAGE_NAME || 'app' }}
    steps:
      - uses: actions/checkout@v4

      # Replace this block for your stack (Node shown as example)
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install & Test
        run: |
          npm ci
          npm test --if-present

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Buildx for multi-arch (M1-safe images)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE }}:testing