name: CI (testing) — Test, Build & Push

on:
  push:
    branches: [ testing ]

jobs:
  test_build_push:
    runs-on: ubuntu-latest
    env:
      ACR_NAME: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
      ACR_LOGIN_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io
    strategy:
      matrix:
        service: [product_service, order_service, customer_service, frontend]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install & Test (skip if no tests)
        run: |
          cd backend/${{ matrix.service }} 2>/dev/null || cd frontend 2>/dev/null || exit 0
          if [ -f package.json ]; then
            npm ci
            npm test --if-present
          fi

      - name: Install & Test Python (if applicable)
        run: |
          cd backend/${{ matrix.service }} 2>/dev/null || exit 0
          if [ -f requirements.txt ]; then
            python -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            pytest --maxfail=1 --disable-warnings -q || true
          fi

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & Push Service
        run: |
          if [ "${{ matrix.service }}" = "frontend" ]; then
            BUILD_PATH=./frontend
          else
            BUILD_PATH=./backend/${{ matrix.service }}
          fi

          docker buildx build --platform linux/amd64 \
            -t ${{ env.ACR_LOGIN_SERVER }}/${{ matrix.service }}:${{ github.sha }} \
            -t ${{ env.ACR_LOGIN_SERVER }}/${{ matrix.service }}:testing \
            $BUILD_PATH --push