# week08/.github/workflows/frontend_ci.yml

name: Frontend CI - Build & Push Image

on:
  # Manual trigger
  workflow_dispatch:

  # Automatically on pushes to main branch
  push:
    branches:
      - main
    paths: # Only trigger if changes are in the frontend directory
      - 'frontend/**'
      - '.github/workflows/frontend_ci.yml' # Trigger if this workflow file changes

# Define global environment variables that can be used across jobs
env:
  # ACR Login Server (e.g., myregistry.azurecr.io)
  # This needs to be set as a GitHub Repository Secret
  ACR_NAME: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
  ACR_LOGIN_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io
  # Dynamically generate image tags based on Git SHA and GitHub Run ID
  # This provides unique, traceable tags for each image build
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_id }}

jobs:
  build_and_push_frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Azure login using a Service Principal secret
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Login to Azure Container Registry (ACR)
    - name: Login to Azure Container Registry
      run: az acr login --name ${{ env.ACR_NAME }}

    # Build and Push multi-arch Docker image for Frontend (Apple Silicon compatible)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Build and push the frontend image with both 'latest' and unique tags for traceability
    - name: Build and Push Frontend Image (Apple Silicon compatible)
      run: |
        docker buildx build --platform linux/amd64 \
          -t ${{ env.ACR_LOGIN_SERVER }}/frontend:latest \
          -t ${{ env.ACR_LOGIN_SERVER }}/frontend:${{ env.IMAGE_TAG }} \
          ./frontend/ \
          --push

    # Logout from Azure for security (runs even if image push fails)
    - name: Logout from Azure
      run: az logout
      if: always()
