name: CD (Production Deploy)

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RG: josephsabana-rg   # change if your Azure resource group is different
      ACR_NAME: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
      ACR_LOGIN_SERVER: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io
      IMAGE_TAG: main
    strategy:
      matrix:
        service: [product_service, order_service, customer_service, frontend]
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Ensure Container Apps extension
        run: az extension add -n containerapp --upgrade --only-show-errors

      - name: Set APP_NAME
        run: echo "APP_NAME=${{ matrix.service//_/-}}-app" >> $GITHUB_ENV

      - name: Create or Update Container App
        run: |
          az containerapp up \
            --name $APP_NAME \
            --resource-group $RG \
            --environment $ACR_NAME-env \
            --image ${{ env.ACR_LOGIN_SERVER }}/${{ matrix.service }}:${{ env.IMAGE_TAG }} \
            --target-port 8000 \
            --ingress external \
            --registry-server ${{ env.ACR_LOGIN_SERVER }} \
            --query properties.configuration.ingress.fqdn