name: Production — Deploy on main

on:
  push:
    branches: [ main ]

jobs:
  deploy_prod:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [product-service, order-service, customer-service, frontend]
    env:
      RG: ${{ secrets.AZ_RESOURCE_GROUP }}
      REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}
      APP_NAME: ${{ secrets.APP_NAME }}-prod
      ENV_NAME: ${{ secrets.PROD_ENV_NAME }}
      IMAGE_TAG: main
      PORT: 8080
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Ensure Container Apps CLI
        run: az extension add -n containerapp --upgrade

      # Option A: keep a 'main' tag in ACR (retag inside ACR)
      - name: Retag testing image as main (in ACR)
        run: |
          az acr import \
            --name ${{ env.REGISTRY }} \
            --source ${{ env.REGISTRY }}/${{ matrix.service }}:testing \
            --image ${{ matrix.service }}:${{ env.IMAGE_TAG }} \
            --force

      # Create if missing, else update image
      - name: Create or update prod app
        run: |
          az containerapp show -n $APP_NAME -g $RG >/dev/null 2>&1 || \
          az containerapp create -n $APP_NAME -g $RG --environment $ENV_NAME \
            --ingress external --target-port $PORT \
            --image ${{ env.REGISTRY }}/${{ matrix.service }}:${{ env.IMAGE_TAG }} \
            --registry-server ${{ env.REGISTRY }} \
            --revision-mode single

          az containerapp update -n $APP_NAME -g $RG \
            --image ${{ env.REGISTRY }}/${{ matrix.service }}:${{ env.IMAGE_TAG }}